name: Building Wheels

on: [workflow_dispatch]

jobs:

  wheel:
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
  
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      
      - name: Install PyTorch
        run: |
          sudo apt update
          sudo apt install "linux-headers-$(uname -r)" "linux-modules-extra-$(uname -r)"
          sudo apt install python3-setuptools python3-wheel
          sudo usermod -a -G render,video $LOGNAME # Add the current user to the render and video groups
          wget https://repo.radeon.com/amdgpu-install/6.3.3/ubuntu/noble/amdgpu-install_6.3.60303-1_all.deb
          sudo apt install ./amdgpu-install_6.3.60303-1_all.deb
          sudo apt update
          sudo apt install amdgpu-dkms rocm
          pip install torch==2.6.0 --extra-index-url https://download.pytorch.org/whl/rocm6.2.4

      - name: Install main package
        run: |
          FORCE_CUDA=1 python setup.py develop
        shell:
          bash
